on:
  issues:
    types: [opened, labeled]
name: Issues
jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ssh-key: "${{secrets.DEPLOY_KEY}}"
    - run: |
        git config --local --unset-all 'http.https://github.com/.extraheader'
        git config --local --name-only --list
    - name: IssueHandler
      uses: ScoopInstaller/Scoop-GithubActions@main
      if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
      env:
        GITH_EMAIL: hoilc@foxmail.com
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
